# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7baaa43438001fe954067c850bdac441bdd7d866414501a39d8cf450eaca229135da180427fb0d6f5850333a03a2b699ec11d3bd2397ce378d773ac1c54f153

test:
  secret_key_base: 3fffc6e7edc011676f79d65deaf052d7783c32e075cc126abefb51b904f4c4a162f3960013cc56f7df7c55dafd5e81b8d992705b0d1ff3d5810ecdee06ec082d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
